### ISSUE TITLE
Support for Zaptec Home?

### ISSUE THREAD

**Issue by jon2com** [PatrickE94/com.zaptec#1]
Will there be support for Zaptec Home?
This is supported in Tibber so should be available in the Zaptec API

thanks
Jon

**Comment by PatrickE94** [comment]
For sure it would be possible to add support for it. However, I don't have a Home so I would need access to someones credentials to try out the API fully.

**Comment by jon2com** [comment]
I will send you a pm on the homey community

**Comment by jon2com** [comment]
I guess I can provide you with that. Let med know how to proceed

Jon

    On Thursday, May 11, 2023 at 09:21:03 PM GMT+2, Patrick Wadström ***@***.***> wrote:  
 
 


For sure it would be possible to add support for it. However, I don't have a Home so I would need access to someones credentials to try out the API fully.

**Comment by leifmagneberland** [comment]
I would love to se a integration with the home version of this charger!

**Comment by PatrickE94** [comment]
Could anyone of you try to use the Pro driver released on the test track of the app? Alternatively, if you're feeling adventreous, go to [Swagger API](https://api.zaptec.com/help/index.html#/Charger/get_api_chargers), authorize using your zaptec credentials in the top right corner and then execute "GET /api/chargers" without parameters (hit "Try it out" to enable the button) and paste the result back here.

**Comment by jon2com** [comment]
Tried the Pro version(1.4.0), but get "No new devices have been found" when trying to add a Zaptec Home charger

**Comment by MVangs** [comment]
> Could anyone of you try to use the Pro driver released on the test track of the app? Alternatively, if you're feeling adventreous, go to [Swagger API](https://api.zaptec.com/help/index.html#/Charger/get_api_chargers), authorize using your zaptec credentials in the top right corner and then execute "GET /api/chargers" without parameters (hit "Try it out" to enable the button) and paste the result back here.

Would love to see support for the "old" Home version as well. I did try Swagger and it seems like it works on mine 
![image](https://github.com/PatrickE94/com.zaptec/assets/71328829/81f348c7-948d-4e5f-8867-cf0f76cb3f28)

**Comment by PatrickE94** [comment]
@MVangs The pro driver in beta testing looks like it should find your device. At least list it. Sadly the "installationType" was not in the response (only in the request filters). Perhaps I'll just strip that filter in beta. Please try it!

@jon2com Device type 0 was a bit unexpected, that's marked as "unknown".  You're getting a lot of 401/403, you sure you got the right credentials?

**Comment by MVangs** [comment]
Thanks, it finds my device now. Have been testing a bit the last day but I'm new to Homey but I get a "Flow Card not registered (type:action, id:pro_installation_curent_control) when using a flow to control the current. Don't know if thats something related to my setup or if its a bug

**Comment by jon2com** [comment]
Now I was able to add it to Homey.
Got the following log:

[2023-10-30T07:19:23.868Z] Renewed token successfully
[2023-10-30T07:19:24.463Z] Charge mode update: 0 to 1
[2023-10-30T07:19:24.511Z] onLastSession fail: Error: Invalid capability (meter_power.last_session) value type. Expected: number. Got: string
[2023-10-30T07:19:24.513Z] Got yearly power history
[2023-10-30T07:19:24.531Z] Got yearly power history
[2023-10-30T07:19:31.692Z] onLastSession fail: Error: Invalid capability (meter_power.last_session) value type. Expected: number. Got: string
[2023-10-30T07:20:00.520Z] onLastSession fail: Error: Invalid capability (meter_power.last_session) value type. Expected: number. Got: string
[2023-10-30T07:20:30.797Z] onLastSession fail: Error: Invalid capability (meter_power.last_session) value type. Expected: number. Got: string

**Comment by jon2com** [comment]
> Thanks, it finds my device now. Have been testing a bit the last day but I'm new to Homey but I get a "Flow Card not registered (type:action, id:pro_installation_curent_control) when using a flow to control the current. Don't know if thats something related to my setup or if its a bug

I get the same error

**Comment by PatrickE94** [comment]
Slight delay here, but I think I've fixed this in the latest beta release.

**Comment by philipostli** [comment]
Perhaps we can get a confirmation that the Home driver is working in the test version, we could push it to Live? @jon2com 
Thanks for testing

**Comment by MVangs** [comment]
Sorry for the slow of response, but yes, the flow card "Set available current to..." is definetly working on the Zaptec Home now.
