### ISSUE TITLE
Start a charge

### ISSUE THREAD

**Issue by celox1** [PatrickE94/com.zaptec#12]
Hi!

I just want to ask a question about the app before i start to troubleshoot :)

Currently my Zaptec Go is in eco mode, so it charges mostly during the night.
But every once in a while i want to start a charge right when I get home.

I have made a simple flow with the "Start Charging" command, but is doesnt "override" the "Charging sheduled at 22:00".

Is this intended? Or is there perhaps another smart way to start a charge without going into the Zaptec App ?
The vision of just screaming at my smart assistant to start a charge is so faboulus :p

**Comment by philipostli** [comment]
Hm. Have you tested overriding in the Zaptec app? From [docs](https://help.zaptec.com/hc/en-001/articles/9556497060753-Eco-Mode):  
> To start a session before the scheduled time, tap Start charging under Home in the app.

Or clicked "Charging" button in the Homey app?

I would think clicking "Start charging" in the app is doing the same as the Homey app. Do you have a firmware version greater than 3.2 ? (found in the [portal](portal.zaptec.com) on the charger, first pane "settings"). This might be the issue. It looks like the Go charger latest version is 2.4.1.2 and do not support resume charging command. 

If you can confirm that resuming charging works in the Zaptec app but not in the Homey app (manual button) we can investigate more.

**Comment by celox1** [comment]
Hi!

Start charging button in the zaptec app works when its scheduled to start at a later time (eco mode).

But the start charging card in homey does not start a charge when its scheduled to start at a later time (eco mode)

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by philipostli** [comment]
I see. I think it is not possible to overrise the Eco mode, unfortunately.

From the [FAQ](https://help.zaptec.com/hc/en-001/articles/9556497060753-Smart-charge-with-Eco-Mode#01GSCJNAHP8PFAHQC6BYGJHSKP):
> Can I use Eco Mode with services like Tibber or Enegic?
> No, Eco Mode requires full control by Zaptec for optimal performance, meaning third-party services will be deactivated while Eco Mode is on and you will not be able to use Smart Charging controls in third-party apps for your Zaptec charger. Once you disable Eco Mode, third-party services will resume control.

**Comment by philipostli** [comment]
Not possible atm so we will close the issue.
