### ISSUE TITLE
Lock cable to charging station

### ISSUE THREAD

**Issue by M-Oberg** [PatrickE94/com.zaptec#4]
It would be nice to have a flow to be able to lock/unlock cable to charging station.

![image](https://github.com/PatrickE94/com.zaptec/assets/16610224/14323a13-c28e-4c15-9216-5598493f285b)

A flow could then look something like:
If car is at home And locked Then lock cable to charging station

**Comment by mortenaggvin** [comment]
In addition, lock/open access to charging would be great. This way, access can be open when you (either user or mode) is at home, while it is locked while you are away. If mode=home/user is present then open charging, else restrict access.

**Comment by philipostli** [comment]
Hey. Just checked with the Zaptec API documentation, and locking cable is not possible yet. I found from another repository that they have added the request to their roadmap, just recently. So we can implement a flow for it (and capability on the charger) once it is available. (Ref. https://github.com/custom-components/zaptec/issues/102)

@mortenaggvin Please open a separate issue with your charge-lock request. Would you mind specify a little bit more what you mean, and why you need this restriction?

**Comment by philipostli** [comment]
Update: Found a way to lock/unlock cable ! Will implement a button as soon as possible. Adding a flow action-card as well.

**Comment by M-Oberg** [comment]
👍
