### ISSUE TITLE
Why only Homey Pro?

### ISSUE THREAD

**Issue by beslu** [PatrickE94/com.zaptec#9]
Hi, 
what is the reason for this app not being compatible with Homey Bridge? 

Regards, Bent

**Comment by PatrickE94** [comment]
Nothing really specific more than Athom requiring me to purchase a verified developer account to publish apps for the Bridge. I have no interest in spending money on app development for Athom.

**Comment by beslu** [comment]
HiThanks for the clarification! Bent S LundTlf 9222622210. juli 2024 kl. 22:51 skrev Patrick Wadström ***@***.***>:﻿
Nothing really specific more than Athom requiring me to purchase a verified developer account to publish apps for the Bridge. I have no interest in spending money on app development for Athom.

**Comment by philipostli** [comment]
@PatrickE94 Have you tried contacting Zaptec about them sponsoring the developer account? It is also possible to make a deal with them if you want to earn a little money. It can be of great value for Zaptec. When people chose their charger, what integrations are available to them can be of great interest. I myself have the Homey Bridge, so I would be interested to use this app too. I have a Zaptec Pro charger and could be interested in contributing to your app. I would be happy if I could run it out of debug mode too. But I will take a look at the code already.

**Comment by philipostli** [comment]
Am closing the issue as we can not do more than try to get Zaptec to approve it as official app.
